program: train_val_test.py
name: open_clip_sweep
description: "Training and evaluating Open CLIP on various datasets"
entity: slytheringe
project: open_clip_sweep
method: random
metric:
  goal: maximize
  name: eval/avg_acc
parameters:
  lr:
    distribution: log_uniform
    min: 1e-9
    max: 1e-4
  warmup:
    distribution: int_uniform
    min: 0
    max: 1000
  wd:
    distribution: uniform
    min: 0.05
    max: 0.2
  accum-freq:
    distribution: int_uniform
    min: 1
    max: 10
  pretrained:
    values: ['laion2B-s32B-b82K', 
            '/mnt/SrvUserDisk/Gejunyao/VLP/open_clip/ckpts/SkyCLIP_ViT_L14_top50pct/epoch_20.pt']
  skyscript-portion:
    distribution: uniform
    min: 0.0
    max: 0.5
  laion-portion:
    distribution: uniform
    min: 0.0
    max: 0.02
  # fixed parameters
  # train-num-samples: 
  #   value: 2000000
  # test-dataset-root: "/mnt/FastDisk/Datasets/RSBenchmarks"
  # model: ViT-L-14
  # datasets-for-testing: "'aid' 'eurosat' 'nwpu' 'millionaid' 'rsicb' 'fmow' 'patternnet' 'SkyScript_cls'"
  # dataset-type: "webdataset"
  # annotation-db: "/mnt/FastDisk/GeJunYao/VLP/databases/annotation.db"
  # report-to: wandb
  # wandb-project-name: open_clip_sweep
  # save-frequency: 1000
  # batch-size: 256
  # use-bn-sync: True
  # epochs: 1
  # workers: 8
  # aug-cfg: 'use_timm=True color_jitter=0.4 scale="(0.67, 1.0)" ratio="(0.5, 2.0)"'
  # gather-with-grad: True
  # log-every-n-steps: 100
  # torchcompile: False
  # train-data: "/mnt/FastDisk/Datasets/RSVLD1M/Patches{0000..0238}.tar::/mnt/FastDisk/Datasets/SkyScript_wds/{0000..0510}.tar::/mnt/SrvDataDisk/DatasetMultiModal/LAION400M/laion400m-data/{00000..04800}.tar" 
  # dataset-resampled: True

command:
  - ${env}
  - torchrun
  - --nproc_per_node=4
  - ${program}
  - ${args}
  - train-num-samples=2000000
  - test-dataset-root="/mnt/FastDisk/Datasets/RSBenchmarks"
  - model=ViT-L-14
  - datasets-for-testing='aid' 'eurosat' 'nwpu' 'millionaid' 'rsicb' 'fmow' 'patternnet' 'SkyScript_cls'
  - dataset-type="webdataset"
  - annotation-db="/mnt/FastDisk/GeJunYao/VLP/databases/annotation.db"
  - report-to=wandb
  - wandb-project-name=open_clip_sweep
  - save-frequency=1000
  - batch-size=256
  - use-bn-sync=True
  - epochs=1
  - workers=8
  - aug-cfg='use_timm=True color_jitter=0.4 scale="(0.67, 1.0)" ratio="(0.5, 2.0)"'
  - gather-with-grad=True
  - log-every-n-steps=100
  - torchcompile=False
  - train-data="/mnt/FastDisk/Datasets/RSVLD1M/Patches{0000..0238}.tar::/mnt/FastDisk/Datasets/SkyScript_wds/{0000..0510}.tar::/mnt/SrvDataDisk/DatasetMultiModal/LAION400M/laion400m-data/{00000..04800}.tar" 
  - dataset-resampled=True
